const API='https://interverse-api-yhqx.onrender.com';
const BUILDER='https://interverse-builder.onrender.com';
const POI_GEOJSON='https://raw.githubusercontent.com/InterVerseSG/interverse-ai/main/knowledge/campus_san_german.geojson';
const GEOMETRY_SOURCES='https://raw.githubusercontent.com/InterVerseSG/interverse-unreal/main/Data/campus_geometry_sources.json';
const OVERPASS='https://overpass-api.de/api/interpreter';

const map=L.map('map',{zoomControl:true}).setView([18.0851,-67.0512],17);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(map);
const poiLayer=L.layerGroup().addTo(map),selectedLayer=L.layerGroup().addTo(map),routeLayer=L.layerGroup().addTo(map),networkLayer=L.layerGroup().addTo(map),buildingLayer=L.layerGroup().addTo(map);
const markerByNav=new Map(),featureByNav=new Map();
let campusBounds=null,selectedNav=null,allFeatures=[];
let routingGraph=null,routingNodes=new Map(),routingReady=false;
let currentRoute=[];
let buildingFootprints=[];

const $=id=>document.getElementById(id);
const statusEl=$('status'),listEl=$('poiList'),commandEl=$('command'),originEl=$('origin');
function setStatus(text,error=false){statusEl.textContent=text;statusEl.className='status'+(error?' error':'');}
function navForFeature(f){return f.properties?.navigation_anchor||`NAV_${f.properties?.id||'Unknown'}`;}
function displayForFeature(f){return f.properties?.display_name||f.properties?.id||'Lugar';}
function hav(a,b){const R=6371000,r=x=>x*Math.PI/180,dLat=r(b.lat-a.lat),dLon=r(b.lng-a.lng);const q=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function fmt(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`;}
function latLngForNav(nav){const f=featureByNav.get(nav);if(!f)return null;const [lon,lat]=f.geometry.coordinates;return L.latLng(lat,lon);}

function showDetails(nav){const f=featureByNav.get(nav);if(!f)return;selectedNav=nav;const [lon,lat]=f.geometry.coordinates;$('details').hidden=false;$('detailsName').textContent=displayForFeature(f);$('detailsNav').textContent=nav;$('detailsCoord').textContent=`${lat.toFixed(6)}, ${lon.toFixed(6)}`;$('detailsStatus').textContent=f.properties?.coordinate_status||'verified';updateDetailsDistance();draw3D();}
function updateDetailsDistance(){const d=$('detailsDistance');if(!selectedNav||!originEl.value){d.textContent='Selecciona origen';return;}const a=latLngForNav(originEl.value),b=latLngForNav(selectedNav);if(a&&b)d.textContent=fmt(hav(a,b));}
function focusNav(nav,message=''){const marker=markerByNav.get(nav);if(!marker){setStatus(`El ancla ${nav} no tiene punto geográfico cargado.`,true);return false;}selectedLayer.clearLayers();const ll=marker.getLatLng();L.circleMarker(ll,{radius:14,weight:4,color:'#FED141',fillColor:'#007B5F',fillOpacity:.25}).addTo(selectedLayer);map.flyTo(ll,19,{duration:.8});marker.openPopup();showDetails(nav);if(message)setStatus(`${message}\nDestino validado: ${nav}`);return true;}

async function checkService(url,dot,state){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error();$(dot).className='dot ok';$(state).textContent='online';}catch{$(dot).className='dot bad';$(state).textContent='offline';}}
function checkServices(){checkService(`${API}/healthz`,'apiDot','apiState');checkService(`${BUILDER}/healthz`,'builderDot','builderState');}

async function loadPOIs(){try{const r=await fetch(POI_GEOJSON,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();const pts=[];allFeatures=(data.features||[]).filter(f=>f.geometry?.type==='Point'&&Array.isArray(f.geometry.coordinates));for(const f of allFeatures){const [lon,lat]=f.geometry.coordinates,name=displayForFeature(f),nav=navForFeature(f);featureByNav.set(nav,f);const marker=L.circleMarker([lat,lon],{radius:7,weight:2,color:'#007B5F',fillColor:'#FED141',fillOpacity:.9}).bindPopup(`<strong>${name}</strong><br><code>${nav}</code><br><small>${lat.toFixed(6)}, ${lon.toFixed(6)}</small>`).addTo(poiLayer);marker.on('click',()=>showDetails(nav));markerByNav.set(nav,marker);pts.push([lat,lon]);const li=document.createElement('li'),btn=document.createElement('button');btn.type='button';btn.innerHTML=`${name}<small>${nav}</small>`;btn.onclick=()=>focusNav(nav,`Destino seleccionado: ${name}`);li.appendChild(btn);listEl.appendChild(li);const opt=document.createElement('option');opt.value=nav;opt.textContent=name;originEl.appendChild(opt);}if(pts.length){campusBounds=L.latLngBounds(pts);map.fitBounds(campusBounds.pad(.12));}const marquis=[...featureByNav.keys()].find(k=>k.toLowerCase().includes('marquis'));if(marquis)originEl.value=marquis;setStatus(`${allFeatures.length} puntos georreferenciados cargados. Preparando geometría y red peatonal…`);await Promise.allSettled([loadBuildingFootprints(),loadWalkingNetwork()]);initCanvas3D();setStatus(`${allFeatures.length} POI cargados · ${buildingFootprints.length} footprints de edificios · ${routingReady?'red peatonal lista':'routing directo de respaldo'}.`);}catch(e){setStatus(`No se pudo cargar el registro geográfico: ${e.message}`,true);}}

async function loadBuildingFootprints(){buildingLayer.clearLayers();buildingFootprints=[];try{const sr=await fetch(GEOMETRY_SOURCES,{cache:'no-store'});if(!sr.ok)throw new Error(`Fuentes HTTP ${sr.status}`);const manifest=await sr.json();const candidates=(manifest.sources||[]).filter(s=>s.source==='OpenStreetMap'&&s.osm_type==='way'&&Number.isFinite(Number(s.osm_id))&&s.geometry_status!=='campus_boundary_available_from_osm');if(!candidates.length)return;const byId=new Map(candidates.map(s=>[Number(s.osm_id),s]));const union=candidates.map(s=>`way(${Number(s.osm_id)});`).join('');const q=`[out:json][timeout:25];(${union});out body geom;`;const r=await fetch(OVERPASS,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw new Error(`Overpass edificios HTTP ${r.status}`);const data=await r.json();for(const way of data.elements||[]){if(way.type!=='way'||!way.tags?.building||!Array.isArray(way.geometry)||way.geometry.length<3)continue;const src=byId.get(Number(way.id));const coords=way.geometry.map(p=>L.latLng(p.lat,p.lon));const height=resolveBuildingHeight(way.tags);const footprint={osmId:Number(way.id),id:src?.id||`OSM_${way.id}`,name:src?.name||way.tags.name||`Edificio OSM ${way.id}`,coords,height,tags:way.tags};buildingFootprints.push(footprint);L.polygon(coords,{color:'#006c54',weight:2,fillColor:'#007B5F',fillOpacity:.20}).bindTooltip(`${footprint.name}<br><small>OSM way ${way.id}${way.tags['building:levels']?` · ${way.tags['building:levels']} niveles`:''}</small>`).addTo(buildingLayer);}draw3D();}catch(e){console.warn('Footprints OSM no disponibles:',e);}}
function resolveBuildingHeight(tags={}){const raw=String(tags.height||'').replace(',','.').match(/[0-9.]+/);if(raw){const h=Number(raw[0]);if(Number.isFinite(h)&&h>1&&h<120)return h;}const levels=Number(tags['building:levels']);if(Number.isFinite(levels)&&levels>0&&levels<30)return levels*3;return 8;}

async function loadWalkingNetwork(){if(!campusBounds)return;const sw=campusBounds.pad(.3).getSouthWest(),ne=campusBounds.pad(.3).getNorthEast();const q=`[out:json][timeout:25];(way[highway~"footway|path|pedestrian|steps|service|residential|living_street"](${sw.lat},${sw.lng},${ne.lat},${ne.lng}););out body;>;out skel qt;`;try{$('routingState').textContent='Cargando red peatonal OSM…';const r=await fetch(OVERPASS,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw new Error(`Overpass HTTP ${r.status}`);const data=await r.json();buildGraph(data);routingReady=routingGraph&&routingGraph.size>0;$('routingState').textContent=routingReady?`Red peatonal lista: ${routingGraph.size} nodos.`:'No se encontró red peatonal; se usará línea directa.';if(routingReady)drawNetworkPreview();}catch(e){routingReady=false;$('routingState').textContent='Red OSM no disponible; se usará línea directa como respaldo.';console.warn(e);}}
function buildGraph(data){routingNodes=new Map();routingGraph=new Map();for(const el of data.elements||[])if(el.type==='node')routingNodes.set(el.id,{id:el.id,lat:el.lat,lon:el.lon});const add=(a,b,w)=>{if(!routingGraph.has(a))routingGraph.set(a,[]);routingGraph.get(a).push([b,w]);};for(const el of data.elements||[]){if(el.type!=='way'||!Array.isArray(el.nodes))continue;for(let i=0;i<el.nodes.length-1;i++){const a=routingNodes.get(el.nodes[i]),b=routingNodes.get(el.nodes[i+1]);if(!a||!b)continue;const w=hav(L.latLng(a.lat,a.lon),L.latLng(b.lat,b.lon));add(a.id,b.id,w);add(b.id,a.id,w);}}}
function drawNetworkPreview(){networkLayer.clearLayers();let drawn=0;for(const [id,edges] of routingGraph){const a=routingNodes.get(id);for(const [bid] of edges){if(id>bid)continue;const b=routingNodes.get(bid);if(a&&b){L.polyline([[a.lat,a.lon],[b.lat,b.lon]],{color:'#007B5F',weight:2,opacity:.16,interactive:false}).addTo(networkLayer);if(++drawn>1200)return;}}}}
function nearestNode(ll){let best=null,dist=Infinity;for(const n of routingNodes.values()){const d=hav(ll,L.latLng(n.lat,n.lon));if(d<dist){dist=d;best=n;}}return best;}
function shortestPath(startId,endId){const dist=new Map([[startId,0]]),prev=new Map(),queue=[[0,startId]];while(queue.length){queue.sort((a,b)=>a[0]-b[0]);const [d,u]=queue.shift();if(d!==dist.get(u))continue;if(u===endId)break;for(const [v,w] of routingGraph.get(u)||[]){const nd=d+w;if(nd<(dist.get(v)??Infinity)){dist.set(v,nd);prev.set(v,u);queue.push([nd,v]);}}}if(!dist.has(endId))return null;const ids=[];for(let u=endId;u!==undefined;u=prev.get(u)){ids.push(u);if(u===startId)break;}ids.reverse();return {ids,distance:dist.get(endId)};}
async function traceRoute(){routeLayer.clearLayers();currentRoute=[];if(!selectedNav){setStatus('Selecciona primero un destino.',true);return;}if(!originEl.value){setStatus('Selecciona primero un punto de origen.',true);return;}const a=latLngForNav(originEl.value),b=latLngForNav(selectedNav);if(!a||!b)return;L.circleMarker(a,{radius:9,color:'#007B5F',fillColor:'#fff',fillOpacity:1,weight:3}).bindTooltip('Origen').addTo(routeLayer);if(routingReady){const s=nearestNode(a),t=nearestNode(b);const route=s&&t?shortestPath(s.id,t.id):null;if(route&&route.ids.length>1){currentRoute=[a,...route.ids.map(id=>{const n=routingNodes.get(id);return L.latLng(n.lat,n.lon);}),b];L.polyline(currentRoute,{color:'#85714D',weight:6,opacity:.9}).addTo(routeLayer);map.fitBounds(L.latLngBounds(currentRoute).pad(.2));const connectors=hav(a,L.latLng(s.lat,s.lon))+hav(b,L.latLng(t.lat,t.lon));const total=route.distance+connectors;updateDetailsDistance();setStatus(`Ruta peatonal OSM trazada.\nDistancia aproximada: ${fmt(total)}.\nDestino: ${selectedNav}`);draw3D();return;}}
currentRoute=[a,b];L.polyline(currentRoute,{color:'#85714D',weight:5,dashArray:'9 8',opacity:.9}).addTo(routeLayer);map.fitBounds(L.latLngBounds(currentRoute).pad(.25));setStatus(`No fue posible resolver una ruta peatonal conectada.\nDistancia directa aproximada: ${fmt(hav(a,b))}.`);draw3D();}

async function runCommand(){const message=commandEl.value.trim();if(!message){setStatus('Escribe una instrucción primero.',true);return;}$('send').disabled=true;setStatus('1/2 Gemini está interpretando la instrucción…');try{const a=await fetch(`${API}/api/v1/assistant`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,context:'InterVerseSG campus web preview',session_id:'web-preview'})});if(!a.ok)throw new Error(`InterVerse API HTTP ${a.status}`);const command=await a.json();setStatus(`1/2 Gemini: ${command.action}\n2/2 Builder está validando…`);const b=await fetch(`${BUILDER}/api/v1/build/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});if(!b.ok)throw new Error(`Builder HTTP ${b.status}`);const v=await b.json();if(!v.accepted)throw new Error(v.message||'Comando rechazado');if(v.action==='navigate'&&v.navigation_anchor){focusNav(v.navigation_anchor,command.response||v.message||'Navegación aceptada.');if(originEl.value)await traceRoute();}else setStatus(`Comando aceptado.\nAcción: ${v.action}\n${command.response||v.message||''}`);}catch(e){setStatus(`La prueba no pudo completarse: ${e.message}`,true);}finally{$('send').disabled=false;}}

let ctx,canvas,yaw=-0.55,pitch=0.75,zoom=1,drag=false,lastX=0,lastY=0;
function initCanvas3D(){canvas=$('threeCanvas');ctx=canvas.getContext('2d');const resize=()=>{const r=$('threeView').getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*devicePixelRatio));canvas.height=Math.max(1,Math.floor(r.height*devicePixelRatio));draw3D();};window.addEventListener('resize',resize);canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lastX)*.008;pitch=Math.max(.25,Math.min(1.3,pitch+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY;draw3D();});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(3,zoom*(e.deltaY>0?.9:1.1)));draw3D();},{passive:false});resize();}
function localXY(ll,center){const R=6371000,rad=Math.PI/180;return {x:(ll.lng-center.lng)*rad*R*Math.cos(center.lat*rad),z:(ll.lat-center.lat)*rad*R};}
function project(p,w,h){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);let x=p.x*cy-p.z*sy,z=p.x*sy+p.z*cy,y=p.y;const y2=y*cp-z*sp,z2=y*sp+z*cp+520/zoom;const s=700/Math.max(80,z2);return {x:w/2+x*s,y:h*.62-y2*s,s};}
function drawPoly(points,fill,stroke){if(points.length<3)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}
function drawBuilding3D(b,center,w,h){const base=b.coords.map(ll=>{const q=localXY(ll,center);return {x:q.x,y:0,z:q.z};});if(base.length<3)return;const top=base.map(p=>({x:p.x,y:b.height,z:p.z}));const pb=base.map(p=>project(p,w,h)),pt=top.map(p=>project(p,w,h));drawPoly(pb,'rgba(0,123,95,.12)','rgba(0,83,65,.50)');for(let i=0;i<pb.length-1;i++){drawPoly([pb[i],pb[i+1],pt[i+1],pt[i]],'rgba(0,123,95,.25)','rgba(0,83,65,.40)');}drawPoly(pt,'rgba(254,209,65,.36)','rgba(0,83,65,.75)');}
function draw3D(){if(!ctx||!allFeatures.length)return;const w=canvas.width/devicePixelRatio,h=canvas.height/devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);const center=campusBounds?campusBounds.getCenter():L.latLng(18.0851,-67.0512);ctx.fillStyle='#e8efe9';ctx.fillRect(0,0,w,h);const grid=80;ctx.strokeStyle='#b7c7c1';ctx.lineWidth=1;for(let i=-6;i<=6;i++){const a=project({x:i*grid,y:0,z:-500},w,h),b=project({x:i*grid,y:0,z:500},w,h);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const c=project({x:-500,y:0,z:i*grid},w,h),d=project({x:500,y:0,z:i*grid},w,h);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke();}
for(const b of buildingFootprints)drawBuilding3D(b,center,w,h);
if(currentRoute.length>1){ctx.strokeStyle='#85714D';ctx.lineWidth=5;ctx.beginPath();currentRoute.forEach((ll,i)=>{const q=localXY(ll,center),p=project({x:q.x,y:4,z:q.z},w,h);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();}
const items=allFeatures.map(f=>{const nav=navForFeature(f),[lon,lat]=f.geometry.coordinates,q=localXY(L.latLng(lat,lon),center);return {f,nav,q,p:project({x:q.x,y:12,z:q.z},w,h)};}).sort((a,b)=>b.p.s-a.p.s);for(const it of items){const sel=it.nav===selectedNav,size=Math.max(5,Math.min(18,it.p.s*(sel?9:6)));ctx.fillStyle=sel?'#FED141':'#007B5F';ctx.fillRect(it.p.x-size/2,it.p.y-size,size,size);ctx.fillStyle='#17211e';ctx.font=`${sel?'bold ':''}12px Arial`;ctx.fillText(displayForFeature(it.f),it.p.x+size/2+4,it.p.y-2);} }

$('send').onclick=runCommand;commandEl.addEventListener('keydown',e=>{if(e.key==='Enter')runCommand();});$('routeSelected').onclick=traceRoute;originEl.onchange=updateDetailsDistance;$('reset').onclick=()=>{selectedLayer.clearLayers();routeLayer.clearLayers();currentRoute=[];if(campusBounds)map.fitBounds(campusBounds.pad(.12));draw3D();};$('view2D').onclick=()=>{$('map').style.display='block';$('threeView').style.display='none';$('view2D').className='compact primary';$('view3D').className='compact secondary';setTimeout(()=>map.invalidateSize(),30);};$('view3D').onclick=()=>{$('map').style.display='none';$('threeView').style.display='block';$('view2D').className='compact secondary';$('view3D').className='compact primary';setTimeout(draw3D,30);};
checkServices();loadPOIs();